class_name InputActions
extends RefCounted

const MOVE_LEFT := &"move_left"
const MOVE_RIGHT := &"move_right"
const MOVE_FORWARD := &"move_forward"
const MOVE_BACKWARD := &"move_backward"
const MOVE_UP := &"move_up"
const MOVE_DOWN := &"move_down"
const MOVE_FAST := &"move_fast"
const INCREASE_MOVE_SPEED := &"increase_move_speed"
const DECREASE_MOVE_SPEED := &"decrease_move_speed"
const TOGGLE_CAMERA_VIEW := &"toggle_camera_view"
const TOGGLE_GRAVITY := &"toggle_gravity"
const TOGGLE_COLLISION := &"toggle_collision"
const QUIT_DEMO := &"quit_demo"
const TOGGLE_UI := &"toggle_ui"
const CYCLE_RENDER_MODE := &"cycle_render_mode"
const TOGGLE_FULLSCREEN := &"toggle_fullscreen"
const TOGGLE_MOUSE_CAPTURE := &"toggle_mouse_capture"
