# Generated by Chisel. Do not edit.
class_name ChiselAssets
extends RefCounted

enum Id {
	FOREST_SOIL_1 = 0,
	FOREST_GRASS_1 = 1,
	FOREST_1_2_K = 2
}

const IDS := [
	"FOREST_SOIL_1",
	"FOREST_GRASS_1",
	"FOREST_1_2_K"
]
const BY_ID := {
	"FOREST_SOIL_1": {
		"category": "terrain_texture",
		"extension": "gppt",
		"height": 1024,
		"name": "forest_soil_1",
		"path": "res://game_data/assets/terrain_texture/forest_soil_1",
		"width": 1024,
		"albedo_height": "res://game_data/assets/terrain_texture/forest_soil_1/albedo_height.png",
		"normal_roughness": "res://game_data/assets/terrain_texture/forest_soil_1/normal_roughness.png"
	},
	"FOREST_GRASS_1": {
		"category": "terrain_texture",
		"extension": "gppt",
		"height": 1024,
		"name": "forest_grass_1",
		"path": "res://game_data/assets/terrain_texture/forest_grass_1",
		"width": 1024,
		"albedo_height": "res://game_data/assets/terrain_texture/forest_grass_1/albedo_height.png",
		"normal_roughness": "res://game_data/assets/terrain_texture/forest_grass_1/normal_roughness.png"
	},
	"FOREST_1_2_K": {
		"category": "hdri",
		"extension": "exr",
		"height": 0,
		"name": "forest_1_2_k",
		"path": "res://game_data/assets/hdri/forest_1_2_k.exr",
		"width": 0
	}
}
