# Generated by Chisel. Do not edit.
class_name ChiselInput
extends RefCounted

const ACTION_NAMES := [
	&"camera_zoom_in",
	&"camera_zoom_out",
	&"escape"
]
const KEY_BINDINGS := {
	"KEY_A": KEY_A,
	"KEY_B": KEY_B,
	"KEY_C": KEY_C,
	"KEY_D": KEY_D,
	"KEY_E": KEY_E,
	"KEY_F": KEY_F,
	"KEY_G": KEY_G,
	"KEY_H": KEY_H,
	"KEY_I": KEY_I,
	"KEY_J": KEY_J,
	"KEY_K": KEY_K,
	"KEY_L": KEY_L,
	"KEY_M": KEY_M,
	"KEY_N": KEY_N,
	"KEY_O": KEY_O,
	"KEY_P": KEY_P,
	"KEY_Q": KEY_Q,
	"KEY_R": KEY_R,
	"KEY_S": KEY_S,
	"KEY_T": KEY_T,
	"KEY_U": KEY_U,
	"KEY_V": KEY_V,
	"KEY_W": KEY_W,
	"KEY_X": KEY_X,
	"KEY_Y": KEY_Y,
	"KEY_Z": KEY_Z,
	"KEY_0": KEY_0,
	"KEY_1": KEY_1,
	"KEY_2": KEY_2,
	"KEY_3": KEY_3,
	"KEY_4": KEY_4,
	"KEY_5": KEY_5,
	"KEY_6": KEY_6,
	"KEY_7": KEY_7,
	"KEY_8": KEY_8,
	"KEY_9": KEY_9,
	"KEY_F1": KEY_F1,
	"KEY_F2": KEY_F2,
	"KEY_F3": KEY_F3,
	"KEY_F4": KEY_F4,
	"KEY_F5": KEY_F5,
	"KEY_F6": KEY_F6,
	"KEY_F7": KEY_F7,
	"KEY_F8": KEY_F8,
	"KEY_F9": KEY_F9,
	"KEY_F10": KEY_F10,
	"KEY_F11": KEY_F11,
	"KEY_F12": KEY_F12,
	"KEY_ESCAPE": KEY_ESCAPE,
	"KEY_SPACE": KEY_SPACE,
	"KEY_SHIFT": KEY_SHIFT,
	"KEY_CTRL": KEY_CTRL,
	"KEY_ALT": KEY_ALT,
	"KEY_TAB": KEY_TAB,
	"KEY_ENTER": KEY_ENTER,
	"KEY_BACKSPACE": KEY_BACKSPACE,
	"KEY_UP": KEY_UP,
	"KEY_DOWN": KEY_DOWN,
	"KEY_LEFT": KEY_LEFT,
	"KEY_RIGHT": KEY_RIGHT,
	"KEY_MINUS": KEY_MINUS,
	"KEY_EQUAL": KEY_EQUAL,
	"KEY_KP_ADD": KEY_KP_ADD,
	"KEY_KP_SUBTRACT": KEY_KP_SUBTRACT
}
const MOUSE_BINDINGS := {
	"MOUSE_BUTTON_LEFT": MOUSE_BUTTON_LEFT,
	"MOUSE_BUTTON_RIGHT": MOUSE_BUTTON_RIGHT,
	"MOUSE_BUTTON_MIDDLE": MOUSE_BUTTON_MIDDLE,
	"MOUSE_BUTTON_WHEEL_UP": MOUSE_BUTTON_WHEEL_UP,
	"MOUSE_BUTTON_WHEEL_DOWN": MOUSE_BUTTON_WHEEL_DOWN
}

static func action_name(action_id: int) -> StringName:
	return ACTION_NAMES[action_id]

static func get_action_strength(action_id: int) -> float:
	return Input.get_action_strength(action_name(action_id))

static func is_action_pressed(action_id: int) -> bool:
	return Input.is_action_pressed(action_name(action_id))

static func is_action_just_pressed(action_id: int) -> bool:
	return Input.is_action_just_pressed(action_name(action_id))

static func is_action_just_released(action_id: int) -> bool:
	return Input.is_action_just_released(action_name(action_id))

func sync_input_map() -> void:
	InputMap.load_from_project_settings()
	for index in range(ACTION_NAMES.size()):
		var input_action_name := action_name(index)
		if InputMap.has_action(input_action_name):
			InputMap.erase_action(input_action_name)
		InputMap.add_action(input_action_name)
		for binding in ChiselInputBindings.BINDINGS[index]:
			var event: Variant = _event_from_binding(String(binding))
			if event is InputEvent:
				InputMap.action_add_event(input_action_name, event)

func _event_from_binding(binding: String) -> Variant:
	if KEY_BINDINGS.has(binding):
		return _key(int(KEY_BINDINGS[binding]))
	if MOUSE_BINDINGS.has(binding):
		return _mouse_button(int(MOUSE_BINDINGS[binding]))

	push_warning("Unsupported Chisel input binding: %s" % binding)
	return null

func _key(keycode: int) -> InputEventKey:
	var event := InputEventKey.new()
	event.keycode = keycode
	return event

func _mouse_button(button_index: int) -> InputEventMouseButton:
	var event := InputEventMouseButton.new()
	event.button_index = button_index
	return event
