# Generated by Chisel. Do not edit.
class_name ChiselLocalization
extends RefCounted


class LocalizedText:
	var plain_text: String
	var bbcode_text: String
	var spans: Array[Dictionary]
	var _tooltips: Dictionary

	func _init(
		next_plain_text: String = "",
		next_bbcode_text: String = "",
		next_spans: Array[Dictionary] = [],
		next_tooltips: Dictionary = {}
	) -> void:
		plain_text = next_plain_text
		bbcode_text = next_bbcode_text
		spans = next_spans
		_tooltips = next_tooltips

	func tooltip_for(term_slug: StringName) -> String:
		return String(_tooltips.get(String(term_slug), ""))


enum Id { UNIT_RIFLE_MAN_NAME = 0, UNIT_RIFLE_MAN_DESCRIPTION = 1 }

const DEFAULT_LOCALE := "en"
const LOCALES := ["en"]
const KEYS := ["UNIT.RIFLE_MAN.NAME", "UNIT.RIFLE_MAN.DESCRIPTION"]
const VALUES := {
	"en":
	[
		"Rifle Man",
		"The unit does [term:PHYSICIAL_DAMAGE] [icon:PHYSICAL_DAMAGE] {float:physical_damage} [/term] points of damage per shot."
	]
}
const ICON_SLUGS := [[], ["PHYSICAL_DAMAGE"]]
const ICONS := {
	"PHYSICAL_DAMAGE":
	{
		"asset_id": "PHYSICAL_DAMAGE",
		"path": "res://game_data/assets/ui_icon/physical_damage.png",
		"width": 2048,
		"height": 2048
	}
}
const PLACEHOLDERS := [[], ["physical_damage"]]
const PLACEHOLDER_TYPES := [[], ["float"]]
const TERMS := {"PHYSICIAL_DAMAGE": {"color": "#ff0000", "tooltip_id": null}}
const CSV_PATH := "res://game_data/localization/translations.csv"


static func format(id: int, arguments: Dictionary = {}, locale: String = "") -> LocalizedText:
	return _format(id, arguments, locale, 0)


static func _format(id: int, arguments: Dictionary, locale: String, depth: int) -> LocalizedText:
	if id < 0 or id >= KEYS.size():
		return LocalizedText.new()
	var locale_key := _locale_key(locale)
	var templates: Array = VALUES.get(locale_key, VALUES[DEFAULT_LOCALE])
	var template := String(templates[id])
	var regex := RegEx.new()
	(
		regex
		. compile(
			"\\[term:([A-Z][A-Z0-9_]*)\\]|\\[/term\\]|\\[icon:([A-Z][A-Z0-9_]*)\\]|\\{(int|float|string):([a-z][a-z0-9_]*)\\}"
		)
	)
	var cursor := 0
	var plain := ""
	var bbcode := ""
	var active_terms: Array[Dictionary] = []
	var spans: Array[Dictionary] = []
	var tooltips := {}
	for result in regex.search_all(template):
		var start := result.get_start(0)
		var end := result.get_end(0)
		var prefix := template.substr(cursor, start - cursor)
		plain += prefix
		bbcode += _bbcode_fragment(prefix, active_terms)
		var token := result.get_string(0)
		if token.begins_with("[term:"):
			active_terms.append({"term": result.get_string(1), "start": plain.length()})
		elif token == "[/term]":
			_close_term(active_terms, spans, tooltips, plain.length(), arguments, locale_key, depth)
		elif token.begins_with("[icon:"):
			var icon_slug := result.get_string(2)
			var icon_start := plain.length()
			plain += _icon_plain(icon_slug)
			bbcode += _icon_fragment(icon_slug, active_terms)
			var icon: Dictionary = ICONS.get(icon_slug, {})
			spans.append(
				{
					"type": "icon",
					"icon": icon_slug,
					"start": icon_start,
					"end": plain.length(),
					"path": String(icon.get("path", ""))
				}
			)
		else:
			var placeholder_type := result.get_string(3)
			var placeholder := result.get_string(4)
			var replacement := str(
				arguments.get(placeholder, _placeholder_default(placeholder_type))
			)
			plain += replacement
			bbcode += _bbcode_fragment(replacement, active_terms)
		cursor = end

	var suffix := template.substr(cursor)
	plain += suffix
	bbcode += _bbcode_fragment(suffix, active_terms)
	while active_terms.size() > 0:
		_close_term(active_terms, spans, tooltips, plain.length(), arguments, locale_key, depth)
	return LocalizedText.new(plain, bbcode, spans, tooltips)


static func _close_term(
	active_terms: Array[Dictionary],
	spans: Array[Dictionary],
	tooltips: Dictionary,
	plain_length: int,
	arguments: Dictionary,
	locale_key: String,
	depth: int
) -> void:
	if active_terms.is_empty():
		return
	var span: Dictionary = active_terms.pop_back()
	var term_slug := String(span.get("term", ""))
	var term: Dictionary = TERMS.get(term_slug, {})
	var tooltip := ""
	var tooltip_id: Variant = term.get("tooltip_id", null)
	if tooltip_id != null and depth < 4:
		tooltip = _format(int(tooltip_id), arguments, locale_key, depth + 1).plain_text
	tooltips[term_slug] = tooltip
	spans.append(
		{
			"term": term_slug,
			"start": int(span.get("start", 0)),
			"end": plain_length,
			"color": _term_color(term_slug),
			"tooltip": tooltip
		}
	)


static func _bbcode_fragment(value: String, active_terms: Array[Dictionary]) -> String:
	var escaped := _bbcode_escape(value)
	var term_slug := _active_term_slug(active_terms)
	var color := _term_color(term_slug)
	if color.is_empty():
		return escaped
	return "[color=%s]%s[/color]" % [color, escaped]


static func _icon_fragment(icon_slug: String, active_terms: Array[Dictionary]) -> String:
	var icon: Dictionary = ICONS.get(icon_slug, {})
	var icon_path := String(icon.get("path", ""))
	if icon_path.is_empty():
		return _bbcode_fragment(_icon_plain(icon_slug), active_terms)
	return "[img]%s[/img]" % _bbcode_escape(icon_path)


static func _icon_plain(icon_slug: String) -> String:
	return "[%s]" % icon_slug


static func _active_term_slug(active_terms: Array[Dictionary]) -> String:
	if active_terms.is_empty():
		return ""
	return String(active_terms[active_terms.size() - 1].get("term", ""))


static func _term_color(term_slug: String) -> String:
	var term: Dictionary = TERMS.get(term_slug, {})
	return String(term.get("color", ""))


static func _placeholder_default(placeholder_type: String) -> Variant:
	if placeholder_type == "int":
		return -1
	if placeholder_type == "float":
		return -1.0
	return "UNKNOWN"


static func _locale_key(locale: String) -> String:
	if not locale.is_empty() and VALUES.has(locale):
		return locale
	var server_locale := TranslationServer.get_locale()
	if VALUES.has(server_locale):
		return server_locale
	var base_locale := server_locale.get_slice("_", 0)
	if VALUES.has(base_locale):
		return base_locale
	return DEFAULT_LOCALE


static func _bbcode_escape(value: String) -> String:
	return value.replace("[", "\\[").replace("]", "\\]")
