# Generated by Chisel. Do not edit.
class_name ChiselGameDataManifest
extends RefCounted

const GENERATED_AT := "2026-07-18T05:49:04.975Z"
const PROJECT_ID := "zYZtnNUg8uht6fA9MFIkW"
const PROJECT_NAME := "Iron Bastion"
const TABLES := {
	"input_bindings":
	{
		"name": "Input Bindings",
		"class_name": "ChiselInputBindings",
		"path": "res://game_data/tables/input_bindings.gd",
		"rows": 6,
		"columns": 2
	}
}
