# Generated by Chisel. Do not edit.
class_name ChiselTranslations
extends RefCounted


class UnitRifleManDescriptionParameters:
	var physical_damage: float = -1.0

	func _init(values: Dictionary = {}) -> void:
		if values.has("physical_damage"):
			physical_damage = float(values["physical_damage"])

	func to_arguments() -> Dictionary:
		return {"physical_damage": physical_damage}


class ItemDeckOfCardsTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_DECK_OF_CARDS_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_DECK_OF_CARDS_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_DECK_OF_CARDS_STORY, {})


class ItemPostcardTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_POSTCARD_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_POSTCARD_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_POSTCARD_STORY, {})


class ItemOldMedalTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_OLD_MEDAL_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_OLD_MEDAL_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_OLD_MEDAL_STORY, {})


class ItemPocketWatchTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_POCKET_WATCH_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_POCKET_WATCH_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_POCKET_WATCH_STORY, {})


class ItemBerserkMushroomsTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_BERSERK_MUSHROOMS_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(
			ChiselLocalization.Id.ITEM_BERSERK_MUSHROOMS_DESCRIPTION, {}
		)

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_BERSERK_MUSHROOMS_STORY, {})


class ItemBattleTonicTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_BATTLE_TONIC_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_BATTLE_TONIC_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_BATTLE_TONIC_STORY, {})


class ItemLeatherGripTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_LEATHER_GRIP_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_LEATHER_GRIP_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_LEATHER_GRIP_STORY, {})


class ItemWhetstoneTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_WHETSTONE_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_WHETSTONE_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_WHETSTONE_STORY, {})


class ItemSteelSwordTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_STEEL_SWORD_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_STEEL_SWORD_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_STEEL_SWORD_STORY, {})


class ItemWoodenShieldTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_WOODEN_SHIELD_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_WOODEN_SHIELD_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_WOODEN_SHIELD_STORY, {})


class ItemSteelArmorTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_STEEL_ARMOR_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_STEEL_ARMOR_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_STEEL_ARMOR_STORY, {})


class ItemMakeshiftArmorTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_MAKESHIFT_ARMOR_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_MAKESHIFT_ARMOR_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_MAKESHIFT_ARMOR_STORY, {})


class ItemTestItemTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_TEST_ITEM_NAME, {})


class ItemTeddyBearTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_TEDDY_BEAR_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_TEDDY_BEAR_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_TEDDY_BEAR_STORY, {})


class ItemUnopenedLiquorTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_UNOPENED_LIQUOR_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_UNOPENED_LIQUOR_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_UNOPENED_LIQUOR_STORY, {})


class ItemBowOldFriendTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_BOW_OLD_FRIEND_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_BOW_OLD_FRIEND_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_BOW_OLD_FRIEND_STORY, {})


class ItemReinforcedBowTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_REINFORCED_BOW_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_REINFORCED_BOW_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_REINFORCED_BOW_STORY, {})


class ItemFireArrowsTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_FIRE_ARROWS_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_FIRE_ARROWS_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_FIRE_ARROWS_STORY, {})


class ItemPiercingArrowsTranslations:
	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_PIERCING_ARROWS_DESCRIPTION, {})

	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_PIERCING_ARROWS_NAME, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_PIERCING_ARROWS_STORY, {})


class ItemHuntingArrowsTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_HUNTING_ARROWS_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_HUNTING_ARROWS_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_HUNTING_ARROWS_STORY, {})


class ItemWaxStringTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_WAX_STRING_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_WAX_STRING_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_WAX_STRING_STORY, {})


class ItemOldRevolverTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_OLD_REVOLVER_NAME, {})

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_OLD_REVOLVER_DESCRIPTION, {})

	func story() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.ITEM_OLD_REVOLVER_STORY, {})


class ItemTranslations:
	var old_revolver := ItemOldRevolverTranslations.new()
	var wax_string := ItemWaxStringTranslations.new()
	var hunting_arrows := ItemHuntingArrowsTranslations.new()
	var piercing_arrows := ItemPiercingArrowsTranslations.new()
	var fire_arrows := ItemFireArrowsTranslations.new()
	var reinforced_bow := ItemReinforcedBowTranslations.new()
	var bow_old_friend := ItemBowOldFriendTranslations.new()
	var unopened_liquor := ItemUnopenedLiquorTranslations.new()
	var teddy_bear := ItemTeddyBearTranslations.new()
	var test_item := ItemTestItemTranslations.new()
	var makeshift_armor := ItemMakeshiftArmorTranslations.new()
	var steel_armor := ItemSteelArmorTranslations.new()
	var wooden_shield := ItemWoodenShieldTranslations.new()
	var steel_sword := ItemSteelSwordTranslations.new()
	var whetstone := ItemWhetstoneTranslations.new()
	var leather_grip := ItemLeatherGripTranslations.new()
	var battle_tonic := ItemBattleTonicTranslations.new()
	var berserk_mushrooms := ItemBerserkMushroomsTranslations.new()
	var pocket_watch := ItemPocketWatchTranslations.new()
	var old_medal := ItemOldMedalTranslations.new()
	var postcard := ItemPostcardTranslations.new()
	var deck_of_cards := ItemDeckOfCardsTranslations.new()


class TooltipPhysicalDamageTypeTranslations:
	func title() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(
			ChiselLocalization.Id.TOOLTIP_PHYSICAL_DAMAGE_TYPE_TITLE, {}
		)

	func description() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(
			ChiselLocalization.Id.TOOLTIP_PHYSICAL_DAMAGE_TYPE_DESCRIPTION, {}
		)


class TooltipTranslations:
	var physical_damage_type := TooltipPhysicalDamageTypeTranslations.new()


class UnitRifleManTranslations:
	func name() -> ChiselLocalization.LocalizedText:
		return ChiselLocalization.format(ChiselLocalization.Id.UNIT_RIFLE_MAN_NAME, {})

	func description(
		parameters: UnitRifleManDescriptionParameters = null
	) -> ChiselLocalization.LocalizedText:
		if parameters == null:
			parameters = UnitRifleManDescriptionParameters.new()
		return ChiselLocalization.format(
			ChiselLocalization.Id.UNIT_RIFLE_MAN_DESCRIPTION, parameters.to_arguments()
		)


class UnitTranslations:
	var rifle_man := UnitRifleManTranslations.new()


static var unit := UnitTranslations.new()
static var tooltip := TooltipTranslations.new()
static var item := ItemTranslations.new()
