#!/usr/bin/env python

from pathlib import Path

godot_cpp_path = Path("godot-cpp")
if not godot_cpp_path.exists():
    raise RuntimeError(
        "Missing graphite/godot-cpp. Clone the Godot C++ bindings there before building."
    )

env = SConscript("godot-cpp/SConstruct")
env.Append(CPPPATH=["include"])
env.Append(CXXFLAGS=["-std=c++17"])

sources = Glob("src/*.cpp")
target_path = "../addons/graphite/bin/libgraphite{}{}".format(
    env["suffix"],
    env["SHLIBSUFFIX"],
)

library = env.SharedLibrary(target_path, source=sources)
Default(library)
