# Generated by Chisel. Do not edit.
class_name ChiselAbility
extends RefCounted

enum Id {}

const TABLE_ID := "45RH7A6GsG12q-v78dmmN"
const TABLE_NAME := "Ability"
const TABLE_KIND := "user"
const SLUGS := []
const NAME := []
const DESCRIPTION := []
const PORTRAIT := []
