# Generated by Chisel. Do not edit.
class_name ChiselBall
extends RefCounted

enum Id {
	INVALID = -1,
	ARCHER_BALL = 0,
	PIKEMAN_BALL = 1,
	KNIGHT_BALL = 2,
	TARGET_PRACTICE_BALL = 3,
	METEOR_STRIKE_BALL = 4
}

const TABLE_ID := "yh7aOYkekni1eI81UEqzn"
const TABLE_NAME := "Ball"
const TABLE_KIND := "user"
const COUNT := 5
const SLUGS := [
	"ARCHER_BALL", "PIKEMAN_BALL", "KNIGHT_BALL", "TARGET_PRACTICE_BALL", "METEOR_STRIKE_BALL"
]
const NAME := [
	ChiselLocalization.Id.BALL_ARCHER_NAME,
	ChiselLocalization.Id.BALL_PIKEMAN_NAME,
	ChiselLocalization.Id.BALL_KNIGHT_NAME,
	ChiselLocalization.Id.BALL_TARGET_PRACTICE_NAME,
	ChiselLocalization.Id.BALL_METEOR_STRIKE_NAME
]
const DESCRIPTION := [
	ChiselLocalization.Id.BALL_ARCHER_DESCRIPTION,
	ChiselLocalization.Id.BALL_PIKEMAN_DESCRIPTION,
	ChiselLocalization.Id.BALL_KNIGHT_DESCRIPTION,
	ChiselLocalization.Id.BALL_TARGET_PRACTICE_DESCRIPTION,
	ChiselLocalization.Id.BALL_METEOR_STRIKE_DESCRIPTION
]
const PORTRAIT := [
	ChiselAssets.Id.ARCHER,
	ChiselAssets.Id.PIKEMAN,
	ChiselAssets.Id.KNIGHT,
	ChiselAssets.Id.TARGET_PRACTICE,
	ChiselAssets.Id.METEOR_STRIKE
]
const KIND := ["UNIT", "UNIT", "UNIT", "ABILITY", "ABILITY"]
const UNIT := [
	ChiselUnit.Id.ARCHER,
	ChiselUnit.Id.PIKEMAN,
	ChiselUnit.Id.KNIGHT,
	ChiselUnit.Id.INVALID,
	ChiselUnit.Id.INVALID
]
const ABILITY := [
	ChiselAbility.Id.INVALID,
	ChiselAbility.Id.INVALID,
	ChiselAbility.Id.INVALID,
	ChiselAbility.Id.TARGET_PRACTICE,
	ChiselAbility.Id.METEOR_STRIKE
]
