# Generated by Chisel. Do not edit.
class_name ChiselBuilding
extends RefCounted

enum Id {
	INVALID = -1,
	BARRACKS = 0,
	ARCHERY_RANGE = 1,
	TREASURY = 2,
	WORKSHOP = 3,
	EMBER_CHAPEL = 4,
	MARKET_STALL = 5
}

const TABLE_ID := "3D2vwVj1UZD_4WoiWoczH"
const TABLE_NAME := "Building"
const TABLE_KIND := "user"
const COUNT := 6
const SLUGS := ["BARRACKS", "ARCHERY_RANGE", "TREASURY", "WORKSHOP", "EMBER_CHAPEL", "MARKET_STALL"]
const NAME := [
	ChiselLocalization.Id.BUILDING_BARRACKS_NAME,
	ChiselLocalization.Id.BUILDING_ARCHERY_RANGE_NAME,
	ChiselLocalization.Id.BUILDING_TREASURY_NAME,
	ChiselLocalization.Id.BUILDING_WORKSHOP_NAME,
	ChiselLocalization.Id.BUILDING_EMBER_CHAPEL_NAME,
	ChiselLocalization.Id.BUILDING_MARKET_STALL_NAME
]
const DESCRIPTION := [
	ChiselLocalization.Id.BUILDING_BARRACKS_DESCRIPTION,
	ChiselLocalization.Id.BUILDING_ARCHERY_RANGE_DESCRIPTION,
	ChiselLocalization.Id.BUILDING_TREASURY_DESCRIPTION,
	ChiselLocalization.Id.BUILDING_WORKSHOP_DESCRIPTION,
	ChiselLocalization.Id.BUILDING_EMBER_CHAPEL_DESCRIPTION,
	ChiselLocalization.Id.BUILDING_MARKET_STALL_DESCRIPTION
]
const PORTRAIT := [
	ChiselAssets.Id.KNIGHT,
	ChiselAssets.Id.ARCHER,
	ChiselAssets.Id.PHYSICAL_DAMAGE,
	ChiselAssets.Id.RANGE,
	ChiselAssets.Id.METEOR_STRIKE,
	ChiselAssets.Id.TARGET_PRACTICE
]
const EFFECT_KEY := [
	"ADD_CARD",
	"COPY_RESULT",
	"ADD_GOLD",
	"ADD_MACHINE_XP",
	"IMPROVE_ASPECT_RECIPES",
	"IMPROVE_SHOP"
]
const MAX_COPIES := [2, 2, 3, 2, 1, 1]
const MAX_LEVEL := [3, 3, 3, 3, 3, 3]
const ASPECT_AFFINITY := [
	ChiselAspect.Id.INVALID,
	ChiselAspect.Id.INVALID,
	ChiselAspect.Id.INVALID,
	ChiselAspect.Id.INVALID,
	ChiselAspect.Id.EMBER,
	ChiselAspect.Id.INVALID
]
