# Generated by Chisel. Do not edit.
class_name ChiselInputBindings
extends RefCounted

enum Id { INVALID = -1, ESCAPE = 0, ACTION = 1, PADDLE_LEFT = 2, PADDLE_RIGHT = 3 }

const TABLE_ID := "input_bindings"
const TABLE_NAME := "Input Bindings"
const TABLE_KIND := "system"
const COUNT := 4
const SLUGS := ["ESCAPE", "ACTION", "PADDLE_LEFT", "PADDLE_RIGHT"]
const SORT_ORDER := [0, 1, 2, 3]
const BINDINGS := [["KEY_ESCAPE"], ["KEY_SPACE"], ["KEY_A", "KEY_LEFT"], ["KEY_D", "KEY_RIGHT"]]
