# Generated by Chisel. Do not edit.
class_name ChiselLne2qvqb0jxtgildudsq4
extends RefCounted

enum Id {}

const TABLE_ID := "LNE2qvQb0jxtgiLDUDsq4"
const TABLE_NAME := "Items"
const TABLE_KIND := "user"
const SLUGS := []
const PRICE := []
