# Generated by Chisel. Do not edit.
class_name ChiselPeg
extends RefCounted

enum Id {
	INVALID = -1,
	EMBER_SIGIL = 0,
	LONGSHOT_MARKER = 1,
	REINFORCEMENT_BANNER = 2,
	WAR_DRUM_PEG = 3,
	OVERCHARGE_RUNE = 4,
	SPRING_PEG = 5,
	SPLITTER_PEG = 6,
	GOLD_CACHE = 7,
	ECHO_SEAL = 8
}

const TABLE_ID := "NwZ2PycvCtTXXvZUQWyXB"
const TABLE_NAME := "Peg"
const TABLE_KIND := "user"
const COUNT := 9
const SLUGS := [
	"EMBER_SIGIL",
	"LONGSHOT_MARKER",
	"REINFORCEMENT_BANNER",
	"WAR_DRUM_PEG",
	"OVERCHARGE_RUNE",
	"SPRING_PEG",
	"SPLITTER_PEG",
	"GOLD_CACHE",
	"ECHO_SEAL"
]
const NAME := [
	ChiselLocalization.Id.PEG_EMBER_SIGIL_NAME,
	ChiselLocalization.Id.PEG_LONGSHOT_MARKER_NAME,
	ChiselLocalization.Id.PEG_REINFORCEMENT_BANNER_NAME,
	ChiselLocalization.Id.PEG_WAR_DRUM_NAME,
	ChiselLocalization.Id.PEG_OVERCHARGE_RUNE_NAME,
	ChiselLocalization.Id.PEG_SPRING_PEG_NAME,
	ChiselLocalization.Id.PEG_SPLITTER_PEG_NAME,
	ChiselLocalization.Id.PEG_GOLD_CACHE_NAME,
	ChiselLocalization.Id.PEG_ECHO_SEAL_NAME
]
const DESCRIPTION := [
	ChiselLocalization.Id.PEG_EMBER_SIGIL_DESCRIPTION,
	ChiselLocalization.Id.PEG_LONGSHOT_MARKER_DESCRIPTION,
	ChiselLocalization.Id.PEG_REINFORCEMENT_BANNER_DESCRIPTION,
	ChiselLocalization.Id.PEG_WAR_DRUM_DESCRIPTION,
	ChiselLocalization.Id.PEG_OVERCHARGE_RUNE_DESCRIPTION,
	ChiselLocalization.Id.PEG_SPRING_PEG_DESCRIPTION,
	ChiselLocalization.Id.PEG_SPLITTER_PEG_DESCRIPTION,
	ChiselLocalization.Id.PEG_GOLD_CACHE_DESCRIPTION,
	ChiselLocalization.Id.PEG_ECHO_SEAL_DESCRIPTION
]
const SYMBOL := [
	ChiselAssets.Id.METEOR_STRIKE,
	ChiselAssets.Id.RANGE,
	ChiselAssets.Id.KNIGHT,
	ChiselAssets.Id.PHYSICAL_DAMAGE,
	ChiselAssets.Id.METEOR_STRIKE,
	ChiselAssets.Id.RANGE,
	ChiselAssets.Id.TARGET_PRACTICE,
	ChiselAssets.Id.KNIGHT,
	ChiselAssets.Id.TARGET_PRACTICE
]
const SYMBOL_COLOR := [
	"#ff5a1f",
	"#4fc3ff",
	"#ffd166",
	"#e63946",
	"#ff8c42",
	"#95d5b2",
	"#b8c0ff",
	"#f9c74f",
	"#c77dff"
]
const KIND := [
	"ASPECT",
	"MODIFIER",
	"MODIFIER",
	"MODIFIER",
	"MODIFIER",
	"PHYSICS",
	"PHYSICS",
	"UTILITY",
	"SPECIAL"
]
const ASPECT := [
	ChiselAspect.Id.EMBER,
	ChiselAspect.Id.INVALID,
	ChiselAspect.Id.INVALID,
	ChiselAspect.Id.INVALID,
	ChiselAspect.Id.INVALID,
	ChiselAspect.Id.INVALID,
	ChiselAspect.Id.INVALID,
	ChiselAspect.Id.INVALID,
	ChiselAspect.Id.INVALID
]
const MODIFIER := [
	ChiselModifier.Id.INVALID,
	ChiselModifier.Id.LONGSHOT_TRAINING,
	ChiselModifier.Id.REINFORCEMENT_CALL,
	ChiselModifier.Id.WAR_DRUM,
	ChiselModifier.Id.OVERCHARGE,
	ChiselModifier.Id.INVALID,
	ChiselModifier.Id.INVALID,
	ChiselModifier.Id.INVALID,
	ChiselModifier.Id.INVALID
]
const PHYSICS_KIND := ["", "", "", "", "", "SPRING", "SPLITTER", "", ""]
const UTILITY_KIND := ["", "", "", "", "", "", "", "GOLD", ""]
const SPECIAL_KIND := ["", "", "", "", "", "", "", "", "ECHO"]
const MAX_LEVEL := [3, 3, 3, 3, 3, 2, 2, 2, 2]
