# Generated by Chisel. Do not edit.
class_name ChiselPeg
extends RefCounted

enum Id {}

const TABLE_ID := "NwZ2PycvCtTXXvZUQWyXB"
const TABLE_NAME := "Peg"
const TABLE_KIND := "user"
const SLUGS := []
const SYMBOL := []
const SYMBOL_COLOR := []
const KIND := []
const UNIT_REF := []
