# Generated by Chisel. Do not edit.
class_name ChiselRecipestep
extends RefCounted

enum Id {}

const TABLE_ID := "7evuGaD29l7vxCpjEVxQf"
const TABLE_NAME := "RecipeStep"
const TABLE_KIND := "user"
const SLUGS := []
const UNIT := []
const ABILITY := []
