# Generated by Chisel. Do not edit.
class_name ChiselRecipe
extends RefCounted

enum Id { INVALID = 0 }

const TABLE_ID := "boRIG5F5aadgs1TVlDgLM"
const TABLE_NAME := "Recipe"
const TABLE_KIND := "user"
const SLUGS := [""]
const RESULT_UNIT := [ChiselUnit.Id.INVALID]
const RESULT_ABILITY := [ChiselAbility.Id.INVALID]
const STEP_1 := [ChiselRecipestep.Id.INVALID]
const STEP_2 := [ChiselRecipestep.Id.INVALID]
