# Generated by Chisel. Do not edit.
class_name ChiselRecipe
extends RefCounted

enum Id { INVALID = -1 }

const TABLE_ID := "boRIG5F5aadgs1TVlDgLM"
const TABLE_NAME := "Recipe"
const TABLE_KIND := "user"
const COUNT := 0
const SLUGS := []
const RESULT_UNIT := []
const RESULT_ABILITY := []
const STEP_1 := []
const STEP_2 := []
