# Generated by Chisel. Do not edit.
class_name ChiselRecipe
extends RefCounted

enum Id {
	INVALID = -1,
	ARCHER_EMBER = 0,
	PIKEMAN_EMBER = 1,
	KNIGHT_EMBER = 2,
	METEOR_EMBER = 3,
	TARGET_PRACTICE_EMBER = 4,
	ARCHER_LONGSHOT = 5,
	PIKEMAN_REINFORCEMENTS = 6,
	KNIGHT_WAR_DRUM = 7,
	METEOR_OVERCHARGE = 8,
	ARCHER_EMBER_LONGSHOT = 9,
	ARCHER_EMBER_REINFORCEMENTS = 10,
	PIKEMAN_EMBER_REINFORCEMENTS = 11,
	KNIGHT_EMBER_WAR_DRUM = 12,
	METEOR_EMBER_OVERCHARGE = 13
}

const TABLE_ID := "boRIG5F5aadgs1TVlDgLM"
const TABLE_NAME := "Recipe"
const TABLE_KIND := "user"
const COUNT := 14
const SLUGS := [
	"ARCHER_EMBER",
	"PIKEMAN_EMBER",
	"KNIGHT_EMBER",
	"METEOR_EMBER",
	"TARGET_PRACTICE_EMBER",
	"ARCHER_LONGSHOT",
	"PIKEMAN_REINFORCEMENTS",
	"KNIGHT_WAR_DRUM",
	"METEOR_OVERCHARGE",
	"ARCHER_EMBER_LONGSHOT",
	"ARCHER_EMBER_REINFORCEMENTS",
	"PIKEMAN_EMBER_REINFORCEMENTS",
	"KNIGHT_EMBER_WAR_DRUM",
	"METEOR_EMBER_OVERCHARGE"
]
const RESULT_UNIT := [
	ChiselUnit.Id.ASHEN_RANGER,
	ChiselUnit.Id.CINDER_PIKEMAN,
	ChiselUnit.Id.FLAME_KNIGHT,
	ChiselUnit.Id.INVALID,
	ChiselUnit.Id.INVALID,
	ChiselUnit.Id.ARCHER,
	ChiselUnit.Id.PIKEMAN,
	ChiselUnit.Id.KNIGHT,
	ChiselUnit.Id.INVALID,
	ChiselUnit.Id.ASHEN_RANGER,
	ChiselUnit.Id.ASHEN_RANGER,
	ChiselUnit.Id.CINDER_PIKEMAN,
	ChiselUnit.Id.FLAME_KNIGHT,
	ChiselUnit.Id.INVALID
]
const RESULT_ABILITY := [
	ChiselAbility.Id.INVALID,
	ChiselAbility.Id.INVALID,
	ChiselAbility.Id.INVALID,
	ChiselAbility.Id.CINDERFALL,
	ChiselAbility.Id.BLAZING_DRILL,
	ChiselAbility.Id.INVALID,
	ChiselAbility.Id.INVALID,
	ChiselAbility.Id.INVALID,
	ChiselAbility.Id.METEOR_STRIKE,
	ChiselAbility.Id.INVALID,
	ChiselAbility.Id.INVALID,
	ChiselAbility.Id.INVALID,
	ChiselAbility.Id.INVALID,
	ChiselAbility.Id.CINDERFALL
]
const STEP_1 := [
	ChiselRecipestep.Id.ARCHER_STEP,
	ChiselRecipestep.Id.PIKEMAN_STEP,
	ChiselRecipestep.Id.KNIGHT_STEP,
	ChiselRecipestep.Id.METEOR_STRIKE_STEP,
	ChiselRecipestep.Id.TARGET_PRACTICE_STEP,
	ChiselRecipestep.Id.ARCHER_STEP,
	ChiselRecipestep.Id.PIKEMAN_STEP,
	ChiselRecipestep.Id.KNIGHT_STEP,
	ChiselRecipestep.Id.METEOR_STRIKE_STEP,
	ChiselRecipestep.Id.ARCHER_STEP,
	ChiselRecipestep.Id.ARCHER_STEP,
	ChiselRecipestep.Id.PIKEMAN_STEP,
	ChiselRecipestep.Id.KNIGHT_STEP,
	ChiselRecipestep.Id.METEOR_STRIKE_STEP
]
const STEP_2 := [
	ChiselRecipestep.Id.EMBER_STEP,
	ChiselRecipestep.Id.EMBER_STEP,
	ChiselRecipestep.Id.EMBER_STEP,
	ChiselRecipestep.Id.EMBER_STEP,
	ChiselRecipestep.Id.EMBER_STEP,
	ChiselRecipestep.Id.LONGSHOT_TRAINING_STEP,
	ChiselRecipestep.Id.REINFORCEMENT_CALL_STEP,
	ChiselRecipestep.Id.WAR_DRUM_STEP,
	ChiselRecipestep.Id.OVERCHARGE_STEP,
	ChiselRecipestep.Id.EMBER_STEP,
	ChiselRecipestep.Id.EMBER_STEP,
	ChiselRecipestep.Id.EMBER_STEP,
	ChiselRecipestep.Id.EMBER_STEP,
	ChiselRecipestep.Id.EMBER_STEP
]
const STEP_3 := [
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.LONGSHOT_TRAINING_STEP,
	ChiselRecipestep.Id.REINFORCEMENT_CALL_STEP,
	ChiselRecipestep.Id.REINFORCEMENT_CALL_STEP,
	ChiselRecipestep.Id.WAR_DRUM_STEP,
	ChiselRecipestep.Id.OVERCHARGE_STEP
]
const STEP_4 := [
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID
]
const STEP_5 := [
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID,
	ChiselRecipestep.Id.INVALID
]
const OFFER_PRIORITY := [
	100,
	95,
	95,
	110,
	100,
	35,
	35,
	35,
	45,
	120,
	115,
	110,
	110,
	130
]
const RECIPE_TIER := [
	1,
	1,
	1,
	2,
	2,
	1,
	1,
	1,
	1,
	2,
	2,
	2,
	2,
	3
]
const COMMAND_COST_DELTA := [
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	2,
	2,
	2,
	2,
	2,
	3
]
