# Generated by Chisel. Do not edit.
class_name ChiselUnit
extends RefCounted

enum Id {
	INVALID = -1,
	ARCHER = 0,
	PIKEMAN = 1,
	KNIGHT = 2,
	ASHEN_RANGER = 3,
	CINDER_PIKEMAN = 4,
	FLAME_KNIGHT = 5
}

const TABLE_ID := "Jt3iVOYOqHl97phbZEpUi"
const TABLE_NAME := "Unit"
const TABLE_KIND := "user"
const COUNT := 6
const SLUGS := [
	"ARCHER",
	"PIKEMAN",
	"KNIGHT",
	"ASHEN_RANGER",
	"CINDER_PIKEMAN",
	"FLAME_KNIGHT"
]
const NAME := [
	ChiselLocalization.Id.UNIT_ARCHER_NAME,
	ChiselLocalization.Id.UNIT_PIKEMAN_NAME,
	ChiselLocalization.Id.UNIT_KNIGHT_NAME,
	ChiselLocalization.Id.UNIT_ASHEN_RANGER_NAME,
	ChiselLocalization.Id.UNIT_CINDER_PIKEMAN_NAME,
	ChiselLocalization.Id.UNIT_FLAME_KNIGHT_NAME
]
const DESCRIPTION := [
	ChiselLocalization.Id.UNIT_ARCHER_DESCRIPTION,
	ChiselLocalization.Id.UNIT_PIKEMAN_DESCRIPTION,
	ChiselLocalization.Id.UNIT_KNIGHT_DESCRIPTION,
	ChiselLocalization.Id.UNIT_ASHEN_RANGER_DESCRIPTION,
	ChiselLocalization.Id.UNIT_CINDER_PIKEMAN_DESCRIPTION,
	ChiselLocalization.Id.UNIT_FLAME_KNIGHT_DESCRIPTION
]
const PORTRAIT := [
	ChiselAssets.Id.ARCHER,
	ChiselAssets.Id.PIKEMAN,
	ChiselAssets.Id.KNIGHT,
	ChiselAssets.Id.ARCHER,
	ChiselAssets.Id.PIKEMAN,
	ChiselAssets.Id.KNIGHT
]
const MAX_HEALTH := [
	80,
	120,
	100,
	75,
	125,
	130
]
const PHYSICAL_ARMOR := [
	0,
	0.1,
	0.15,
	0,
	0.1,
	0.15
]
const ATTACK_DAMAGE := [
	15,
	30,
	20,
	22,
	38,
	30
]
const ATTACK_RATE := [
	1.2,
	1,
	1.3,
	1,
	0.95,
	1.2
]
const ATTACK_RANGE := [
	6.4,
	2.1,
	1.7,
	6.8,
	2.2,
	1.7
]
const COMMAND_COST := [
	1,
	1,
	1,
	2,
	2,
	2
]
const BASE_UNIT_COUNT := [
	1,
	1,
	1,
	1,
	1,
	1
]
